# -*- coding: utf-8 -*-
"""co2 emission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2tksLNds8r1cWio25OP_nGcAMHCECa4
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import joblib

df=pd.read_csv("/content/sustainability_data.csv")

df.head()

df.tail()

df.tail()

df.describe()

df.info()

df.isnull().sum()

df.sample(5)

x=df[["Year","Energy_Consumption","Renewable_Percentage","GDP"]]
y=df["CO2_Emissions"]
print(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.83,random_state=8)
x_train

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print(f"mean squared error:{mse}")
print(f"r-squared: {r2}")

joblib.dump(model,'co2_Emission_predictor.pkl')

model=joblib.load("co2_Emission_predictor.pkl")

new_data_array=np.array([[2026,600,28.3333,1800]])
new_data = pd.DataFrame(new_data_array, columns=x.columns)

predicted_output=model.predict(new_data)
print(f"predicted co2 emission outputt:{predicted_output[0]} watts")