# -*- coding: utf-8 -*-
"""solar_power_output.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXur0Qe9EF0Jlj42tAWIymskhWLp2cSy
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import joblib

df=pd.read_csv("/content/solar_power_output (1).csv")

df.head()

df.tail()

df.shape

df.columns

df.info()

df.describe

df.isnull().sum()

df.dtypes

df["humidity"]

df.sample(5)

x = df[['temperature','humidity','solar_irradiance','wind_speed']]
y = df['solar_power_output']
print(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)
x_train

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print(f"mean squared error:{mse}")
print(f"r-squared: {r2}")

joblib.dump(model,'solar_power_prediction_model.pkl')

model=joblib.load("solar_power_prediction_model.pkl")

new_data_array=np.array([[19.36,75.85,266.61,5.19]])
new_data = pd.DataFrame(new_data_array, columns=x.columns)

predicted_output=model.predict(new_data)
print(f"predicted solar power outputt:{predicted_output[0]} watts")